AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: either
